# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{be9-viewtastic}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Istvan Hoka", "Oleg Dashevskii"]
  s.date = %q{2011-05-24}
  s.email = %q{olegdashevskii@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "History.txt",
    "LICENSE",
    "lib/duck_punches/array/each_with_presenter.rb",
    "lib/viewtastic.rb",
    "lib/viewtastic/activation.rb",
    "lib/viewtastic/base.rb",
    "lib/viewtastic/test_case.rb"
  ]
  s.homepage = %q{http://github.com/be9/viewtastic}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Presenter implementation for Ruby on Rails 3.x}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

