# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{viewtastic}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Istvan Hoka"]
  s.date = %q{2010-09-06}
  s.email = %q{istvan.hoka@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "History.txt",
     "LICENSE",
     "lib/duck_punches/array/each_with_presenter.rb",
     "lib/viewtastic.rb",
     "lib/viewtastic/activation.rb",
     "lib/viewtastic/base.rb",
     "lib/viewtastic/test_case.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/ihoka/viewtastic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Presenter plugin for Ruby on Rails}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

